export const constants = {
    NumFormat: "0,0",
    DateFormat: "DD/MM/YYYY",
    DateTimeFormat: "DD/MM/YYYY HH:mm",
    DateTimeFormatFromDB: "YYYY-MM-DD HH:mm:ss",
    DatePickerFormat: "DD/MM/YYYY",
    DateFormatFromDB: "YYYY-MM-DD",
    TimeFormat: "HH:mm",
    MinDateDefault: "0001-01-01 00:00:00",
    MinDateDefaultISOFormat: "0001-01-01T00:00:00",
    EmptyGuidId: '00000000-0000-0000-0000-000000000000',
    ErrorDefinedPrefix: "Error Defined: ",
    ForeignKey: "foreign",
    EmailExsits: "taken",
    DuplicateEntry: "duplicate",
    Slash: '/',
    //--------------Login constants-----------------
    LastTimeAPICalled: "LastedTimeCallAPI",
    AuthenKey: "AccessToken",
    Email: "Email",
    CurrentUserName: "CurrentUserName",
    CurrentUserId: "CurrentUserId",
    DefaultPathName: "DefaultPathName",
    AccessibleProperties: "AccessibleProperties",
    TokenExpiration: "TokenExpiration",
    RefreshToken: "RefreshToken",
    ValidTo: "ValidTo",
    IsRoleAllowChangeSIC: "IsRoleAllowChangeSIC",
    ReturnUrl: "ReturnUrl",
    ReturnUrlId: "ReturnUrlId",
    ErrorTimeRefreshToken: 30000,
    TimeToDirectToLoginPage: 5000,
    FullName: "FullName",
    //-----------------------------------------------
    ImageFileAccept: ".gif,.jpg,.jpeg,.png",
    NoPermissions: {
        view: 'view',
        create: 'create',
        update: 'update',
        delete: 'delete',
    },
    Permissions: {
        view: 1,
        create: 2,
        update: 3,
        delete: 4
    },
    ActionGridItemWidth: 49,
};