export const constants = {
    NumFormat: "0,0",
    DateFormat: "DD/MM/YYYY",
    DateTimeFormat: "DD/MM/YYYY HH:mm",
    DateTimeFormatFromDB: "YYYY-MM-DD HH:mm:ss",
    DatePickerFormat: "DD/MM/YYYY",
    DateFormatFromDB: "YYYY-MM-DD",
    TimeFormat: "HH:mm",
    MinDateDefault: "0001-01-01 00:00:00",
    MinDateDefaultISOFormat: "0001-01-01T00:00:00",
    EmptyGuidId: '00000000-0000-0000-0000-000000000000',
    ErrorDefinedPrefix: "Error Defined: ",
    ForeignKey: "foreign",
    EmailExsits: "taken",
    DuplicateEntry: "duplicate",
    Slash: '/',
    LastTimeAPICalled: "MICE_LastedTimeCallAPI",
    AuthenKey: "mice",
    Email: "email",
    CurrentUserName: "MICE_CurrentUserName",
    CurrentUserId: "MICE_CurrentUserId",
    DefaultPathName: "MICE_DefaultPathName",
    AccessibleProperties: "MICE_AccessibleProperties",
    TokenExpiration: "MICE_TokenExpiration",
    ValidTo: "MICE_ValidTo",
    IsRoleAllowChangeSIC: "MICE_IsRoleAllowChangeSIC",
    ReturnUrl: "MICE_ReturnUrl",
    ReturnUrlId: "MICE_ReturnUrlId",
    ErrorTimeRefreshToken: 30000,
    TimeToDirectToLoginPage: 5000,
    ImageFileAccept: ".gif,.jpg,.jpeg,.png",
    Permissions: {
        View: 1,
        Insert: 2,
        Update: 3,
        Delete: 4
    },
    ActionGridItemWidth: 49,
};