import React, { Fragment } from 'react';
import { useTranslation } from "react-i18next";
import { Button } from "antd";
import useReactRouter from 'use-react-router';

export const ANoOfMiceBookingStatus = () => {
    const {t} = useTranslation();
    const {history} = useReactRouter();

    const onHandleClick = () => {
        history.push('/dashboard');
    };
    return (
        <Fragment>
            <div>...
                <br/>
                <br/>
                <Button type="primary" onClick={onHandleClick}>Push To DashBoard</Button>
                <br/>
                <br/>
                {t('general.errorGeneral')}
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                long
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                content
            </div>
        </Fragment>
    );
};