export const dashboard_en = {
    bookingListTab: "Booking List",
    accommodationListTab: "Accommodation List",
    btnLinkViewMoreA: "View more",
    btnLinkViewMoreB: "Report: MICE revenue by components",
    btnLinkViewMoreC: "Report: No of MICE bookings and revenue by salesman",
    btnLinkViewMoreD: "Report: No of Mice bookings and revenue by industry",
    btnLinkViewMoreE: "Report: No of MICE bookings by account (link to account list)",
    btnLinkViewCalendar: "View Event Calendar",
    searchPlaceHolder: "Bkg.ID/ Bkg.Name/ Acc.Name",
    searchSalesNamePlaceHolder: "SalesName/SalesArea",
    btnLinkViewBookingList: "View Booking List",
    eventListTab: "Event List",
    searchAccommodationPlaceHolder: "Bkg.ID/ Ope.ID/ Acc.Name",
    btnLinkViewMoreF: "Report: No of accommodation bookings by account",
    reportMiceBookingByStatus: "Bookings By Status",
    reportMiceRevenueByComponent: "Revenue By Components",
    reportBookingAndRevenueBySalesMan: "Bookings And Revenue By Sales",
    reportBookingAndRevenueByIndustry: "Bookings And Revenue By Industry",
    guestRoomTypeCalendar: "Accommodation Bookings By Account",
    searchPlaceHolderActivityHistory: "Bkg.ID/ Bkg.Name",
};

export const dashboard_vn = {
    bookingListTab: "Booking List",
    accommodationListTab: "Accommodation List",
    btnLinkViewMoreA: "View more",
    btnLinkViewMoreB: "Report: MICE revenue by components",
    btnLinkViewMoreC: "Report: No of MICE bookings and revenue by salesman",
    btnLinkViewMoreD: "Report: No of Mice bookings and revenue by industry",
    btnLinkViewMoreE: "Report: No of MICE bookings by account (link to account list)",
    btnLinkViewCalendar: "View Event Calendar",
    searchPlaceHolder: "Bkg.ID/ Bkg.Name/ Acc.Name",
    searchSalesNamePlaceHolder: "SalesName/SalesArea",
    btnLinkViewBookingList: "View Booking List",
    eventListTab: "Event List",
    searchAccommodationPlaceHolder: "Bkg.ID/ Ope.ID/ Acc.Name",
    btnLinkViewMoreF: "Report: No of accommodation bookings by account",
    reportMiceBookingByStatus: "Bookings By Status",
    reportMiceRevenueByComponent: "Revenue By Components",
    reportBookingAndRevenueBySalesMan: "Bookings And Revenue By Sales",
    reportBookingAndRevenueByIndustry: "Bookings And Revenue By Industry",
    guestRoomTypeCalendar: "Accommodation Bookings By Account",
    searchPlaceHolderActivityHistory: "Bkg.ID/ Bkg.Name",
};