export const general_en = {
    errorGeneral: "Something wrong!",
    errorMessageIsUse: "Data in used!",
    errorEmailExist: "Email is exist",
    errorDuplicateEntry: " is existed",
    success: "Success",
    failed: "Failed",
    messageSuccess: "Success",
    messageFailed: "Failed",
    fillUpErrorField: "Please correct error fields before submit",
    errorItemNotFoundOrNotHadPermission: "Not found or Not had permission",
    error: "Error",
    errorImageUpload: "Upload error or type's file not support. Please check it.",
    errorFileOverLimit: "Upload maximum {0} files",
    search: "Search",
    titlePopUpAdd: "Add",
    titlePopUpEdit: "Edit",
    titlePopUpDelete: "Delete",
    deletePopUpTitle: "Delete record?",
    deletePopUpBody: "Do you really want to delete selected record?",
    btnClear: "Clear",
    btnClose: "Close",
    btnSave: "Save",
    createdBy: "Created",
    modifiedBy: "Latest update",
    createModifiedAt: " at ",
    createModifiedBy: " by ",
};

export const general_vn = {
    errorGeneral: "Lỗi phát sinh!",
    errorMessageIsUse: "Dữ liệu đang được sử dụng",
    errorEmailExist: "Email đã được sử dụng",
    errorDuplicateEntry: " đã tồn tại",
    success: "Thành công",
    failed: "Thất bại",
    messageSuccess: "Thành công",
    messageFailed: "Thất bại",
    fillUpErrorField: "Please correct error fields before submit",
    errorItemNotFoundOrNotHadPermission: "Not found or Not had permission",
    error: "Error",
    errorImageUpload: "Upload error or type's file not support. Please check it.",
    errorFileOverLimit: "Upload maximum {0} files",
    search: "Search",
    titlePopUpAdd: "Thêm",
    titlePopUpEdit: "Chỉnh sửa",
    titlePopUpDelete: "Xoá",
    deletePopUpTitle: "Xoá dữ liệu?",
    deletePopUpBody: "Bạn có chắc chắn xoá dữ liệu?",
    btnClear: "Clear",
    btnClose: "Close",
    btnSave: "Save",
    createdBy: "Created",
    modifiedBy: "Latest update",
    createModifiedAt: " at ",
    createModifiedBy: " by ",
};