export const general_en = {
    errorGeneral: "Something wrong!",
    errorMessageIsUse: "Data in used!",
    errorEmailExist: "Email is exist",
    errorDuplicateEntry: " is existed",
    success: "Success",
    failed: "Failed",
    messageSuccess: "Success",
    messageFailed: "Failed",
    fillUpErrorField: "Please correct error fields before submit",
    errorItemNotFoundOrNotHadPermission: "Not found or Not had permission",
    error: "Error",
    errorImageUpload: "Upload error or type's file not support. Please check it.",
    errorFileOverLimit: "Upload maximum {0} files",
    search: "Search",
    titlePopUpAdd: "Add",
    titlePopUpEdit: "Edit",
    titlePopUpDelete: "Delete",
    deletePopUpTitle: "Delete record?",
    deletePopUpBody: "Do you really want to delete selected record?",
    btnClear: "Clear",
    btnClose: "Close",
    btnSave: "Save",
    createdBy: "Created",
    modifiedBy: "Latest update",
    createModifiedAt: " at ",
    createModifiedBy: " by ",
    multipleSelect: {
        property: {
            all: "All Properties",
            no: "No property selected",
            many: "%s properties selected",
        },
        chain: {
            all: "All Chains",
            no: "No chain selected",
            many: "%s chains selected",
        },
        area: {
            all: "All Areas",
            no: "No area selected",
            many: "%s areas selected",
        },
        categories: {
            all: "All Categories",
            no: "No category selected",
            many: "%s categories selected",
        },
    },
    ddlPropertyPlaceHolder: "Choose property",
    ddlServicePlaceHolder: "Choose service",
    errorPhoneNumber: "Phone number must at least 10 characters, max 11 characters",
    permissionError: "You do not have permission",
};

export const general_vn = {
    errorGeneral: "Lỗi phát sinh!",
    errorMessageIsUse: "Dữ liệu đang được sử dụng",
    errorEmailExist: "Email đã được sử dụng",
    errorDuplicateEntry: " đã tồn tại",
    success: "Thành công",
    failed: "Thất bại",
    messageSuccess: "Thành công",
    messageFailed: "Thất bại",
    fillUpErrorField: "Please correct error fields before submit",
    errorItemNotFoundOrNotHadPermission: "Not found or Not had permission",
    error: "Error",
    errorImageUpload: "Upload error or type's file not support. Please check it.",
    errorFileOverLimit: "Upload maximum {0} files",
    search: "Search",
    titlePopUpAdd: "Thêm",
    titlePopUpEdit: "Chỉnh sửa",
    titlePopUpDelete: "Xoá",
    deletePopUpTitle: "Xoá dữ liệu?",
    deletePopUpBody: "Bạn có chắc chắn xoá dữ liệu?",
    btnClear: "Clear",
    btnClose: "Close",
    btnSave: "Save",
    createdBy: "Created",
    modifiedBy: "Latest update",
    createModifiedAt: " at ",
    createModifiedBy: " by ",
    multipleSelect: {
        property: {
            all: "Tất cả các cơ sở",
            no: "Không cơ sở được chọn",
            many: "%s cơ sở được chọn",
        },
        chain: {
            all: "Tất cả các chuỗi",
            no: "Không chuỗi được chọn",
            many: "%s chuỗi được chọn",
        },
        area: {
            all: "Tất cả các khu vực",
            no: "Không khu vực được chọn",
            many: "%s khu vực được chọn",
        },
        categories: {
            all: "Tất cả các thể loại",
            no: "Không thể loại được chọn",
            many: "%s thể loại được chọn",
        },
    },
    ddlPropertyPlaceHolder: "Chọn cơ sở",
    ddlServicePlaceHolder: "Chọn dịch vụ",
    errorPhoneNumber: "Số điện thoại không hợp lệ",
    permissionError: "You do not have permission",
};